version: 1.2
workflows:
  - name: influenza_assembly
    subclass: WDL
    primaryDescriptorPath: /workflows/influenza_assembly.wdl
  - name: influenza_assembly_summary
    subclass: WDL
    primaryDescriptorPath: /workflows/influenza_assembly_summary.wdl
